version: '3.8'

services:
  backend:
    image: peekachiu/my-trip-backend:latest
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  frontend:
    image: peekachiu/my-trip-frontend:latest
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    depends_on:
      - backend
